### ISSUE TITLE
Usar selectores de clase en lugar de etiqueta

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/d-s1-evaluacion-intermedia-veronicabautista#2]
Salvo el body, con el que haremos una excepción, siempre usaremos selectores de clase. Te animas a añadirlos?

![Pleeeease](https://media.giphy.com/media/mrZcf6eYn3bz2/giphy.gif)

**Comment by veronicabautista** [comment]
¡Si me lo pide ese gatito por supuesto!
