### ISSUE TITLE
Como pincelada final, ajustamos la estructura de carpetas y archivos?

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/d-s1-evaluacion-intermedia-veronicabautista#4]
En la sesión 1.1 os proponemos una estructura para los proyectos: https://books.adalab.es/materiales-front-end-d/sprint-1.-hola-mundo/1.1.-intro-a-la-web#notas-finales-sobre-como-organizar-nuestro-proyecto

La aplicamos?

![Últimas pinceladas](https://media.giphy.com/media/n5vlIXw4XBgGc/giphy.gif)

**Comment by veronicabautista** [comment]
¡¡HECHO!! 
https://media1.tenor.com/images/93f0dcf24e545a46f3b2a42c0be24ba3/tenor.gif?itemid=10265457
